#!/usr/bin/env python3
"""
verify_hit.py — validate a claimed GPU hit against the CPU reference.

Use this EVERY TIME the GPU reports a hit before committing to tx assembly.
Catches silent divergence between GPU kernel logic and CPU pipeline.

Usage:
    python3 verify_hit.py pin --locktime 12345 --sequence 0xfffffffe
    python3 verify_hit.py digest --round 1 --indices 1,4,9,23,55,77,89,101,121
    python3 verify_hit.py digest --round 2 --indices 0,7,33,41,62,88,99,110,130

Inputs:
    State file:    qsb_state.json       (produced by `setup`)
    Round params:  gpu_digest_r{1,2}_params.json  (produced by `export`)
    Pin params:    gpu_pinning_params.json        (produced by `export`)

All of these are in the same directory where `setup` and `export` were run.

Exit code 0 = hit is genuine, safe to use.
Exit code non-zero = claimed hit doesn't reproduce → STOP, do not assemble tx.
"""
import argparse
import hashlib
import json
import struct
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / 'pipeline'))
sys.path.insert(0, str(Path(__file__).resolve().parent))

from bitcoin_tx import (  # type: ignore
    Transaction, TxIn, TxOut, find_and_delete, push_data, encode_der_sig,
)
from secp256k1 import (  # type: ignore
    N as CURVE_N, P as CURVE_P, ecdsa_recover,
)

def h2b(s): return bytes.fromhex(s)
def b2h(b): return b.hex()
from gpu_emulator import (
    emulate_pinning, emulate_digest_round, puzzle_hash, is_valid_der,
    compress_pubkey,
)


def _check_params_format(params, kind):
    """Abort if the params file predates the layout fix."""
    if kind == 'digest' and 'pre_hors_section' not in params:
        print(f"ERROR: gpu_digest_r*_params.json is in the OLD format "
              f"(pre-layout-fix). Re-run `qsb_pipeline.py export` to produce "
              f"the new format. Silently continuing would produce a wrong "
              f"sighash and accept a fake hit.")
        sys.exit(2)
    if kind == 'pinning' and 'combined_suffix' not in params and 'pin_prefix' not in params:
        # Old pinning format — sighash reconstruction in verify_pin rebuilds
        # from state anyway so this is actually fine; just warn.
        pass


def load_state(dir_path='.'):
    with open(Path(dir_path) / 'qsb_state.json') as f:
        return json.load(f)


def verify_pin(args):
    """Validate a pinning hit: given (locktime, sequence), did the GPU get a
    valid DER sig_puzzle? Rerun on CPU, compare byte-for-byte.

    If --gpu-hit-file is supplied, also reads GPU-reported pubkey/sha/sighash
    and compares to CPU-computed values, localizing any divergence.
    """
    state = load_state(args.work_dir)
    params_file = Path(args.work_dir) / 'gpu_pinning_params.json'
    if not params_file.exists():
        print(f"ERROR: {params_file} not found. Run `export` first.")
        return 1
    with open(params_file) as f:
        params = json.load(f)

    # The params exported an embedded locktime/sequence in tx_prefix. Re-export
    # or override with the hit's values. Simpler: rebuild the preimage from
    # scratch using the full state + the claimed locktime/sequence.
    hash_mode = state.get('hash_mode', 'sha256')
    full_script = h2b(state['full_script_hex'])
    pin_sig = h2b(state['pin_sig'])
    pin_r = state['pin_r']
    pin_s = state['pin_s']

    # Rebuild pinning scriptCode (F&D of pin_sig)
    pin_script_code = find_and_delete(full_script, pin_sig)

    # Reconstruct the spending tx EXACTLY from gpu_pinning_params.json's
    # 'spending_tx' record (saved at export time). This way verify_hit
    # always uses the same structure the kernel hashed against, with no
    # need for the user to repeat all those CLI args.
    sp = params.get('spending_tx')
    if sp is None:
        print(f"ERROR: gpu_pinning_params.json was generated by an old "
              f"export (no 'spending_tx' field). Re-run `export` with the "
              f"new --extra-input-* and --output-* flags.")
        return 1
    extra_txid = h2b(sp['extra_input']['txid'])[::-1]
    funding_txid = h2b(sp['qsb_input']['txid'])[::-1]
    tx = Transaction(version=sp['version'], locktime=args.locktime)
    tx.add_input(TxIn(extra_txid, sp['extra_input']['vout'], b'',
                       sp['extra_input']['sequence']))
    tx.add_input(TxIn(funding_txid, sp['qsb_input']['vout'], b'',
                       args.sequence))
    tx.add_output(TxOut(sp['output']['value'],
                         h2b(sp['output']['script_pubkey'])))
    QSB_INPUT_INDEX = sp.get('qsb_input_index', 1)

    # Sighash for the QSB input with pin_script_code, SIGHASH_ALL
    z_int = tx.sighash(QSB_INPUT_INDEX, pin_script_code, sighash_type=0x01)

    # Optional: read GPU-reported diagnostics from hit file
    gpu_pubkey = None
    gpu_sha_pk = None
    gpu_sighash = None
    if getattr(args, 'gpu_hit_file', None):
        with open(args.gpu_hit_file) as f:
            for line in f:
                line = line.strip()
                if line.startswith('gpu_pubkey='):
                    gpu_pubkey = h2b(line.split('=', 1)[1])
                elif line.startswith('gpu_sha_pk='):
                    gpu_sha_pk = h2b(line.split('=', 1)[1])
                elif line.startswith('gpu_sighash='):
                    gpu_sighash = h2b(line.split('=', 1)[1])

    # EC recovery — try all 4 (recid, r_try) combinations
    found = None
    candidates = []  # all attempted; for diagnostic
    for r_try in [pin_r] + ([pin_r + CURVE_N] if pin_r + CURVE_N < CURVE_P else []):
        for recid in [0, 1]:
            pt = ecdsa_recover(r_try, pin_s, z_int, recid)
            if pt is None:
                continue
            pk = compress_pubkey(pt)
            h, valid, hc = puzzle_hash(pk, hash_mode)
            candidates.append({
                'recid': recid, 'r_try': r_try, 'hash_choice': hc,
                'pubkey': pk, 'puzzle_hash': h, 'valid_der': valid,
            })
            if valid and not found:
                found = candidates[-1]

    print("=" * 60)
    print(f"PIN HIT verification for locktime={args.locktime} "
          f"sequence=0x{args.sequence:08x}")
    print("=" * 60)
    print(f"  CPU sighash (z):  {z_int:064x}")
    if gpu_sighash is not None:
        match = (gpu_sighash == z_int.to_bytes(32, 'big'))
        print(f"  GPU sighash:      {gpu_sighash.hex()}  {'(MATCH)' if match else '(DIFFERS!)'}")
    if found:
        print(f"  recid:            {found['recid']}")
        print(f"  r_try:            {found['r_try']:064x}")
        print(f"  hash_choice:      {found['hash_choice']}")
        print(f"  CPU pubkey:       {b2h(found['pubkey'])}")
        if gpu_pubkey is not None:
            match = (gpu_pubkey == found['pubkey'])
            print(f"  GPU pubkey:       {b2h(gpu_pubkey)}  {'(MATCH)' if match else '(DIFFERS!)'}")
        print(f"  CPU puzzle_hash:  {b2h(found['puzzle_hash'])}")
        if gpu_sha_pk is not None:
            match = (gpu_sha_pk == found['puzzle_hash'])
            print(f"  GPU puzzle_hash:  {b2h(gpu_sha_pk)}  {'(MATCH)' if match else '(DIFFERS!)'}")
        print(f"  valid DER:        YES")
        print()
        print("✅ HIT CONFIRMED — locktime reproduces a valid DER sig_puzzle.")
        return 0
    print(f"  No CPU recovery produced a valid DER hash with this (locktime, seq).")
    if gpu_pubkey is not None or gpu_sha_pk is not None:
        print()
        print("  CPU vs GPU comparison (helps localize the bug):")
        for c in candidates:
            print(f"    recid={c['recid']}, hash_choice={c['hash_choice']}:")
            print(f"      CPU pubkey:      {b2h(c['pubkey'])}")
            if gpu_pubkey is not None and c['recid'] == 0 + 0:  # show both
                pass
            print(f"      CPU puzzle_hash: {b2h(c['puzzle_hash'])}  valid={c['valid_der']}")
        if gpu_pubkey is not None:
            print(f"    GPU pubkey:        {b2h(gpu_pubkey)}")
            # Check if GPU's pubkey equals any of the CPU's recoveries
            cpu_pks = [c['pubkey'] for c in candidates]
            if gpu_pubkey in cpu_pks:
                print(f"    → matches one of CPU's pubkeys; DIVERGENCE is downstream "
                      f"(SHA or DER check).")
            else:
                print(f"    → does NOT match any CPU pubkey; DIVERGENCE is in EC recovery.")
        if gpu_sha_pk is not None:
            print(f"    GPU SHA256(pk):    {b2h(gpu_sha_pk)}")
            cpu_hs = [c['puzzle_hash'] for c in candidates]
            if gpu_sha_pk in cpu_hs:
                print(f"    → SHA256 matches CPU; DIVERGENCE is in DER check itself.")
    print()
    print("❌ HIT DOES NOT REPRODUCE — do NOT assemble tx with these values.")
    return 1


def verify_digest(args):
    """Validate a digest-round hit: given a subset, did the GPU get a valid DER?"""
    state = load_state(args.work_dir)
    ri = args.round - 1  # 0-indexed
    indices = sorted(int(x) for x in args.indices.split(','))
    t = state[f't{args.round}s'] + state[f't{args.round}b']
    if len(indices) != t:
        print(f"ERROR: expected {t} indices for round {args.round}, got {len(indices)}")
        return 1

    params_file = Path(args.work_dir) / f'gpu_digest_r{args.round}_params.json'
    if not params_file.exists():
        print(f"ERROR: {params_file} not found. Run `export` first.")
        return 1
    with open(params_file) as f:
        params = json.load(f)
    _check_params_format(params, 'digest')

    # Inject hash_mode if not present (older params files may lack it)
    params['hash_mode'] = state.get('hash_mode', 'sha256')

    # Run the emulator. Pass the CLI args.sequence and args.locktime so the
    # emulator patches tx_suffix the same way the GPU kernel does at runtime.
    # Without this the emulator would compute a sighash using whatever
    # placeholder seq/lt were baked into gpu_digest_rN_params.json at export
    # time — which differs from what the kernel actually hashed.
    out = emulate_digest_round(params, indices, sighash_type=0x01,
                                sequence=args.sequence,
                                locktime=args.locktime)

    # Now cross-check: rebuild the preimage via the CPU pipeline's pattern and
    # verify the emulator agrees.
    hash_mode = state['hash_mode']
    full_script = h2b(state['full_script_hex'])
    sig_nonce = h2b(state['round_sigs'][ri]['sig'])
    sc = find_and_delete(full_script, sig_nonce)
    for idx in indices:
        dummy_sig = h2b(state['dummy_sigs'][ri][idx])
        sc = find_and_delete(sc, dummy_sig)

    funding_txid = h2b(args.funding_txid)[::-1]
    sp = params.get('spending_tx')
    if sp is None:
        print(f"ERROR: gpu_digest_r{args.round}_params.json was generated by an "
              f"old export (no 'spending_tx' field). Re-run `export` with the "
              f"new --extra-input-* and --output-* flags.")
        return 1
    extra_txid = h2b(sp['extra_input']['txid'])[::-1]
    tx = Transaction(version=sp['version'], locktime=args.locktime)
    tx.add_input(TxIn(extra_txid, sp['extra_input']['vout'], b'',
                       sp['extra_input']['sequence']))
    tx.add_input(TxIn(funding_txid, sp['qsb_input']['vout'], b'', args.sequence))
    tx.add_output(TxOut(sp['output']['value'],
                         h2b(sp['output']['script_pubkey'])))
    QSB_INPUT_INDEX = sp.get('qsb_input_index', 1)

    z_cpu = tx.sighash(QSB_INPUT_INDEX, sc, sighash_type=0x01)
    z_emu = int.from_bytes(out['sighash'], 'big')

    print("=" * 60)
    print(f"DIGEST ROUND {args.round} HIT verification")
    print("=" * 60)
    print(f"  Indices:      {indices}")
    print(f"  Locktime:     {args.locktime}")
    print(f"  Sequence:     0x{args.sequence:08x}")
    print()
    print(f"  Emulator sighash:  {z_emu:064x}")
    print(f"  CPU sighash:       {z_cpu:064x}")

    if z_cpu != z_emu:
        print()
        print("❌ SIGHASH MISMATCH between emulator and CPU pipeline!")
        print("   This means the GPU input files or CPU pipeline have a bug.")
        print("   DO NOT use this hit.")
        return 1
    print("  ✓ sighashes match")

    hit = out['hit']
    if hit is None:
        print()
        print("❌ No candidate produced a valid DER. This is NOT a real hit.")
        print("   (The GPU may have reported a false positive or stale data.)")
        return 1

    print(f"  recid:         {hit['recid']}")
    print(f"  hash_choice:   {hit['hash_choice']}")
    print(f"  pubkey:        {b2h(hit['pubkey'])}")
    print(f"  puzzle_hash:   {b2h(hit['puzzle_hash'])}")
    print(f"  valid DER:     YES")
    print()
    print(f"✅ HIT CONFIRMED for round {args.round}, subset {indices}")
    return 0


def main():
    ap = argparse.ArgumentParser(
        description="Verify a claimed GPU hit against the CPU reference")
    ap.add_argument('--work-dir', default='.',
                    help="Directory containing qsb_state.json + gpu_*_params.json")
    sub = ap.add_subparsers(dest='mode', required=True)

    p_pin = sub.add_parser('pin', help='Verify a pinning-search hit')
    p_pin.add_argument('--locktime', type=int, required=True)
    p_pin.add_argument('--sequence', type=lambda x: int(x, 0), required=True,
                       help='0x-prefix OK')
    p_pin.add_argument('--version', type=int, default=1)
    p_pin.add_argument('--funding-txid', required=True,
                       help='funding tx id (big-endian hex)')
    p_pin.add_argument('--funding-vout', type=int, default=0)
    p_pin.add_argument('--gpu-hit-file', default=None,
                       help='Optional: pinning_hit_<gpu>.txt file from GPU. '
                            'If provided, compares GPU-reported pubkey/sha/sighash '
                            'to CPU-computed values to localize divergence.')

    p_dig = sub.add_parser('digest', help='Verify a digest-round hit')
    p_dig.add_argument('--round', type=int, required=True, choices=[1, 2])
    p_dig.add_argument('--indices', required=True,
                       help='comma-separated subset (sorted ascending)')
    p_dig.add_argument('--locktime', type=int, required=True)
    p_dig.add_argument('--sequence', type=lambda x: int(x, 0), required=True)
    p_dig.add_argument('--version', type=int, default=1)
    p_dig.add_argument('--funding-txid', required=True)
    p_dig.add_argument('--funding-vout', type=int, default=0)

    args = ap.parse_args()

    if args.mode == 'pin':
        return verify_pin(args)
    if args.mode == 'digest':
        return verify_digest(args)
    return 2


if __name__ == '__main__':
    sys.exit(main())
